POST http://localhost:3333/customer
Content-Type: application/json

{
  "name": "Tatyane",
  "email": "taty@test.com"
}

### 
GET http://localhost:3333/customers

### 
DELETE http://localhost:3333/customer/67ca2d19b1007b59fef7ac4d